### ISSUE TITLE
Kubernetes "K3S" not working

### ISSUE THREAD

**Issue by manishie** [Qovery/terraform-examples#2]
Hi,

In main.tf:
```
resource "qovery_cluster" "my_cluster" {
  ...
  kubernetes        = "K3S"
  ...
}

```
should work, as per the [API docs](https://api-doc.qovery.com/#tag/Clusters/operation/createCluster).

I'm getting this error:
`An argument named "kubernetes" is not expected here.`

Thanks!

**Comment by acarranoqovery** [comment]
Hi @manishie , sorry for this very late reply but this has been fixed long time ago but the property is called [kubernetes_mode](https://registry.terraform.io/providers/Qovery/qovery/latest/docs/resources/cluster#kubernetes_mode)
